### ISSUE TITLE
Setup script on server incomplete. Missing lots of dependencies.

### ISSUE THREAD

**Issue by johnny-wang16** [AGI-Labs/manimo#39]
After running the installation script `source setup_manimo_env_server.sh` on NUC, there are still a lot of dependencies missing that prevents successful execution of `python get_current_position.py`

For example, 
Traceback (most recent call last):
  File "/home/franka/manimo/manimo/scripts/get_current_position.py", line 4, in <module>
    from manimo.environments.single_arm_env import SingleArmEnv
ModuleNotFoundError: No module named 'manimo'

I think[ this part of the dependency](https://github.com/mihdalal/manimo/blob/e93fb6742582095154d99b5ea2b598356cb47ec3/setup_manimo_env_client.sh#L26C1-L34C53) should be copied over.

**Comment by johnny-wang16** [comment]
seems like all these are missing in the setup script for NUC:

```
pip install gym
pip install hydra-core==1.2.0
pip install dm-robotics-moma==0.5.0 --no-deps
pip install dm-robotics-transformations==0.5.0 --no-deps
pip install dm-robotics-agentflow==0.5.0 --no-deps
pip install dm-robotics-geometry==0.5.0 --no-deps
pip install dm-robotics-manipulation==0.5.0 --no-deps
pip install dm-robotics-controllers==0.5.0 --no-deps
pip install mujoco==2.3.2 --no-deps
pip install protobuf==3.20.3
pip install dm-control==1.0.5
pip install protobuf==3.20.3
pip install -e .

```

**Comment by mohanksriram** [comment]
Hi, please note that we expect manimo to be installed on the client machine. you should be calling `python get_current_position.py` on the client.
